/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meninblack1;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import meninblack1.Database;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author clara
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminLabelEmail = new javax.swing.JLabel();
        adminLabelPassword = new javax.swing.JLabel();
        adminEntryEmail = new javax.swing.JTextField();
        adminEntryPassword = new javax.swing.JTextField();
        adminButtonLogin = new javax.swing.JButton();
        adminButtonForgot = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        messageBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminLabelEmail.setText("Email");

        adminLabelPassword.setText("Password");

        adminEntryEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminEntryEmailActionPerformed(evt);
            }
        });

        adminButtonLogin.setText("Login");
        adminButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonLoginActionPerformed(evt);
            }
        });

        adminButtonForgot.setBackground(new java.awt.Color(242, 242, 242));
        adminButtonForgot.setText("Forgot credentials");
        adminButtonForgot.setBorder(null);
        adminButtonForgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonForgotActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Admin login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminLabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminButtonForgot))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(adminButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(messageBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(adminEntryPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminEntryEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminLabelEmail)
                    .addComponent(adminEntryEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminLabelPassword)
                    .addComponent(adminEntryPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminButtonLogin)
                    .addComponent(adminButtonForgot)
                    .addComponent(messageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminEntryEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminEntryEmailActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_adminEntryEmailActionPerformed

    private void adminButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonLoginActionPerformed
        // TODO add your handling code here:
        // Reset the messageBox to clear any previous messages
        messageBox.setText("");
        boolean check = true;
        
        String email = adminEntryEmail.getText();
         // Validate the email using a custom validation method (Validering.isValidEmail)
        if(!Validering.isValidEmail(email)){
            check = false;
            messageBox.setText("Email Error");
        }

        String password = adminEntryPassword.getText();
         // Validate the password using a custom validation method (Validering.isValidPassword)
        if(!Validering.isValidPassword(password)){
            check = false;
            messageBox.setText("Password Error");
        }
        try {

            String emailQuery = "SELECT Epost FROM agent";
            String loginQuery = "SELECT Losenord FROM agent WHERE Epost = '" + email + "'";
            // Fetch the list of emails from the database
            ArrayList<String> emails = Database.getDatabase().fetchColumn(emailQuery);
            Boolean emailCheck = false;
            Boolean passwordCheck = false;
            String adminQuery = "select Administrator from agent where Epost = '" + email + "'";
            
            //
            String adminRight = Database.getDatabase().fetchSingle(adminQuery);
            System.out.println(adminRight);
            if (adminRight.equals("N")) {
                check = false;
                messageBox.setText("No admin right");
            }
            //
            
            // Check if the entered email exists in the list of emails
            for (String oneEmail: emails){
                if(oneEmail.equals(email)){
                    emailCheck = true;
                    
                }
            }
             // Check if the entered password matches the password in the database
            if(password.equals(Database.getDatabase().fetchSingle(loginQuery))){
                passwordCheck = true; 
            }
            else{
                messageBox.setText("Wrong email and password");
                passwordCheck = false;
            }
            if(emailCheck && passwordCheck && check){
                // Set the shared data using DataHolder to carry the email information
                DataHolder.getInstance().setSharedData(email);
                AdminStartWindow frame = new AdminStartWindow();
                frame.setVisible(true);
                dispose();
            }
        }catch(InfException ex){
            Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }//GEN-LAST:event_adminButtonLoginActionPerformed

    private void adminButtonForgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonForgotActionPerformed
        // TODO add your handling code here:
        AlienResetCredentials frame = new AlienResetCredentials();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_adminButtonForgotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButtonForgot;
    private javax.swing.JButton adminButtonLogin;
    private javax.swing.JTextField adminEntryEmail;
    private javax.swing.JTextField adminEntryPassword;
    private javax.swing.JLabel adminLabelEmail;
    private javax.swing.JLabel adminLabelPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField messageBox;
    // End of variables declaration//GEN-END:variables
}
