/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meninblack1;
import java.util.ArrayList;

/**
 *
 * @author maxli
 */
public class AdminStartWindow extends javax.swing.JFrame {

    /**
     * Creates new form AdminStartWindow
     */
    public AdminStartWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        registerNewAlienButton = new javax.swing.JButton();
        giveAdminStatusButton = new javax.swing.JButton();
        updateAgentInfoButton = new javax.swing.JButton();
        listAgentsByLocation = new javax.swing.JButton();
        addNewAgentButton = new javax.swing.JButton();
        removeEquipmentButton = new javax.swing.JButton();
        changeBossButton = new javax.swing.JButton();
        changeBossOfLocation = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        removeAgentButton = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Admin Access");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        registerNewAlienButton.setText("Register new alien");
        registerNewAlienButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerNewAlienButtonActionPerformed(evt);
            }
        });

        giveAdminStatusButton.setText("Give admin status");
        giveAdminStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveAdminStatusButtonActionPerformed(evt);
            }
        });

        updateAgentInfoButton.setText("Update agent info");
        updateAgentInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAgentInfoButtonActionPerformed(evt);
            }
        });

        listAgentsByLocation.setText("List agent info");
        listAgentsByLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAgentsByLocationActionPerformed(evt);
            }
        });

        addNewAgentButton.setText("Register new agent");
        addNewAgentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewAgentButtonActionPerformed(evt);
            }
        });

        removeEquipmentButton.setText("Remove equipment");
        removeEquipmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEquipmentButtonActionPerformed(evt);
            }
        });

        changeBossButton.setText("Change boss of Orebro");
        changeBossButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBossButtonActionPerformed(evt);
            }
        });

        changeBossOfLocation.setText("Change boss of location");
        changeBossOfLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBossOfLocationActionPerformed(evt);
            }
        });

        jButton1.setText("Remove alien");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update alien info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        removeAgentButton.setText("Remove agent");
        removeAgentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAgentButtonActionPerformed(evt);
            }
        });

        back.setText("Log out");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(removeAgentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updateAgentInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addNewAgentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(registerNewAlienButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(removeEquipmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeBossButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeBossOfLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(giveAdminStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listAgentsByLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewAgentButton)
                    .addComponent(registerNewAlienButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(updateAgentInfoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(removeAgentButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listAgentsByLocation)
                .addGap(8, 8, 8)
                .addComponent(changeBossButton)
                .addGap(11, 11, 11)
                .addComponent(changeBossOfLocation)
                .addGap(12, 12, 12)
                .addComponent(removeEquipmentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(giveAdminStatusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(back)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerNewAlienButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerNewAlienButtonActionPerformed
        // TODO add your handling code here:
        AdminAddNewAlien frame = new AdminAddNewAlien();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_registerNewAlienButtonActionPerformed

    private void giveAdminStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giveAdminStatusButtonActionPerformed
        // TODO add your handling code here:
        AdminGiveAdminStatus frame = new AdminGiveAdminStatus();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_giveAdminStatusButtonActionPerformed

    private void updateAgentInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAgentInfoButtonActionPerformed
        // TODO add your handling code here:
        AdminChangeAgentInfo frame = new AdminChangeAgentInfo();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_updateAgentInfoButtonActionPerformed

    private void listAgentsByLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAgentsByLocationActionPerformed
        // TODO add your handling code here:
        AdminListAnAgentInfo frame = new AdminListAnAgentInfo();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_listAgentsByLocationActionPerformed

    private void addNewAgentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewAgentButtonActionPerformed
        // TODO add your handling code here:
        AdminAddNewAgent frame = new AdminAddNewAgent();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_addNewAgentButtonActionPerformed

    private void removeEquipmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEquipmentButtonActionPerformed
        // TODO add your handling code here:
        AdminRemoveEquipment frame = new AdminRemoveEquipment();
        frame.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_removeEquipmentButtonActionPerformed

    private void changeBossButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBossButtonActionPerformed
        // TODO add your handling code here:
        AdminChangeBossOfOffice frame = new AdminChangeBossOfOffice();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_changeBossButtonActionPerformed

    private void changeBossOfLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBossOfLocationActionPerformed
        // TODO add your handling code here:
        AdminChangeBossOfLocation frame = new AdminChangeBossOfLocation();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_changeBossOfLocationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AdminRemoveAlien frame = new AdminRemoveAlien();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AdminChangeAlienInformation frame = new AdminChangeAlienInformation();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void removeAgentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAgentButtonActionPerformed
        // TODO add your handling code here:
        AdminRemoveAgent frame = new AdminRemoveAgent();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_removeAgentButtonActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        StartWindow frame = new StartWindow();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminStartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminStartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminStartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminStartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminStartWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewAgentButton;
    private javax.swing.JButton back;
    private javax.swing.JButton changeBossButton;
    private javax.swing.JButton changeBossOfLocation;
    private javax.swing.JButton giveAdminStatusButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listAgentsByLocation;
    private javax.swing.JButton registerNewAlienButton;
    private javax.swing.JButton removeAgentButton;
    private javax.swing.JButton removeEquipmentButton;
    private javax.swing.JButton updateAgentInfoButton;
    // End of variables declaration//GEN-END:variables
}
