/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meninblack1;
import java.util.ArrayList;
import oru.inf.InfException;

/**
 *
 * @author maxli
 */
public class AgentAddNewEquipment_new extends javax.swing.JFrame {

    /**
     * Creates new form RegisterNewEquipment
     */
    public AgentAddNewEquipment_new() {
        initComponents();
        setId();
        fillCB();
    }
    public void setId() {
        try {
            String counter = Database.getDatabase().getAutoIncrement("utrustning", "utrustnings_ID");
            equipmentIDEntry.setText(counter);
        } catch (InfException ex) {
            System.out.println(ex);
        }
    }
    private void fillCB(){
        cb.addItem("Teknik");
        cb.removeItem("Item 1");
        cb.removeItem("Item 2");
        cb.removeItem("Item 3");
        cb.removeItem("Item 4");
        
        cb.addItem("Kommunikation");
        cb.addItem("Vapen");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        equipmentIDEntry = new javax.swing.JTextField();
        equipmentNameEntry = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addNewEquipmentButton = new javax.swing.JButton();
        goBack = new javax.swing.JButton();
        cb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        descVariable = new javax.swing.JTextField();
        entryVariable = new javax.swing.JTextField();
        message = new javax.swing.JTextField();
        messageBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Put in new equipment details");

        jLabel2.setText("Equipment ID");

        jLabel3.setText("Equipment name");

        addNewEquipmentButton.setText("Add");
        addNewEquipmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewEquipmentButtonActionPerformed(evt);
            }
        });

        goBack.setText("Back");
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });

        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });

        jLabel4.setText("Type of weapon");

        message.setBackground(new java.awt.Color(204, 204, 204));
        message.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(61, 61, 61)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(equipmentNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(equipmentIDEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(66, 66, 66)
                                        .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(descVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(goBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addNewEquipmentButton)
                                    .addComponent(entryVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(messageBox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equipmentIDEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(equipmentNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(goBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entryVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addNewEquipmentButton)
                            .addComponent(messageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewEquipmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewEquipmentButtonActionPerformed
        // TODO add your handling code here:
        boolean check = true; //
        boolean checkInsertIntoSubclass = true;
        try {
            int equipmentID = Integer.parseInt(equipmentIDEntry.getText());
            String equipmentName = equipmentNameEntry.getText();
            if(!Validering.isNameLetters(equipmentName)){ //isNameLetters retunerar sant om det är ett namn, därför negerar vi den för att if-statement att triggas.
                messageBox.setText("Enter valid name");
                check = false;
            }
            ArrayList<String> weaponNames = Database.getDatabase().fetchColumn("select Benamning from utrustning");
            for (String name : weaponNames) {
                if (equipmentName.equals(name)) {
                    check = false;
                }
            }
            String insertQuery = "insert into utrustning values (" + equipmentID + ", '" + equipmentName + "')";
            String typeOfTool = cb.getSelectedItem().toString();
            if (check) {
                switch (typeOfTool) {
                    case "Teknik" -> {
                        descVariable.setText("Enter kraftkalla");
                        String variableOver = entryVariable.getText();
                        if(!Validering.isNameLetters(variableOver)){
                            checkInsertIntoSubclass = false;
                            messageBox.setText("Kraftkalla error");
                            descVariable.setText("Enter kraftkalla");
                        }
                        String insertTech = "insert into teknik values (" + equipmentID + ", '" + variableOver + "')";
                        if(checkInsertIntoSubclass){
                            Database.getDatabase().insert(insertQuery);
                            Database.getDatabase().insert(insertTech);
                            messageBox.setText("Equipment added");
                            equipmentNameEntry.setText("");
                            descVariable.setText("");
                        }
                    }
                    case "Kommunikation" -> {
                        descVariable.setText("Enter Overforningsteknik");
                        String variableKraft = entryVariable.getText();
                        if(!Validering.isNameLetters(variableKraft)){
                            checkInsertIntoSubclass = false;
                            messageBox.setText("Overforningsteknik error");
                            descVariable.setText("Enter Overforningsteknik");
                        }
                        String insertCom = "insert into kommunikation values (" + equipmentID + ", '" + variableKraft + "')";
                        if(checkInsertIntoSubclass){
                            Database.getDatabase().insert(insertQuery);
                            Database.getDatabase().insert(insertCom);
                            messageBox.setText("Equipment added");
                            equipmentNameEntry.setText("");
                            descVariable.setText("");
                        }
                    }
                    case "Vapen" -> {
                        descVariable.setText("Enter Kaliber");
                        String variableWeapon = entryVariable.getText();
                        if(!Validering.isNumber(variableWeapon)){
                            checkInsertIntoSubclass = false;
                            messageBox.setText("Kaliber error");
                            descVariable.setText("Enter Kaliber");
                        }
                        String insertWeapon = "insert into vapen values (" + equipmentID + ", '" + variableWeapon + "')";
                        if(checkInsertIntoSubclass){
                            Database.getDatabase().insert(insertQuery);
                            Database.getDatabase().insert(insertWeapon);
                            messageBox.setText("Equipment added");
                            equipmentNameEntry.setText("");
                            descVariable.setText("");
                        }
                    }
                }
                entryVariable.setText("");
                
                
            }else if(equipmentName.isEmpty()){
                messageBox.setText("Enter equipment name");
            }
            else{
                messageBox.setText("Weapon is already in list");
            }
            setId();
            
        } catch (InfException ex) {
            System.out.println("Fel med" + ex);
        }
    }//GEN-LAST:event_addNewEquipmentButtonActionPerformed

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed
        // TODO add your handling code here:
        AgentStartWindow frame = new AgentStartWindow();
        frame.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_goBackActionPerformed

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
        // TODO add your handling code here:
        String selection = cb.getSelectedItem().toString();
        System.out.println(selection);
        switch (selection) {
            case "Teknik":
                descVariable.setText("Enter kraftkalla");
                break;
            case "Kommunikation":
                descVariable.setText("Enter Overforningsteknik");
                break;
            case "Vapen":
                descVariable.setText("Enter Kaliber");
                break;
        }
    }//GEN-LAST:event_cbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentAddNewEquipment_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentAddNewEquipment_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentAddNewEquipment_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentAddNewEquipment_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentAddNewEquipment_new().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewEquipmentButton;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JTextField descVariable;
    private javax.swing.JTextField entryVariable;
    private javax.swing.JTextField equipmentIDEntry;
    private javax.swing.JTextField equipmentNameEntry;
    private javax.swing.JButton goBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField message;
    private javax.swing.JTextField messageBox;
    // End of variables declaration//GEN-END:variables
}
