/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meninblack1;

/**
 *
 * @author clara
 */
public class AgentStartWindow extends javax.swing.JFrame {

    /**
     * Creates new form AgentStartWindow
     */
    public AgentStartWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgentLableAccess = new javax.swing.JLabel();
        agentButtonChangeAlienInfo = new javax.swing.JButton();
        AgentButtonListaAlien = new javax.swing.JButton();
        AgentButtonRegisterAlien = new javax.swing.JButton();
        AgentButtonRegisterEquippment = new javax.swing.JButton();
        AgentButtonAlienInfo = new javax.swing.JButton();
        AgentButtonAreaManager = new javax.swing.JButton();
        AgentButtonStatisticsOfAgent = new javax.swing.JButton();
        agentButtonCheckedOutEquippment = new javax.swing.JButton();
        agentButtonShowListOfAlienRace = new javax.swing.JButton();
        agentButtonStatisticsOfRegisteredAliens = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 300));

        AgentLableAccess.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AgentLableAccess.setText("Agent Access");

        agentButtonChangeAlienInfo.setText("Change Alien Info");
        agentButtonChangeAlienInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentButtonChangeAlienInfoActionPerformed(evt);
            }
        });

        AgentButtonListaAlien.setText("List Alien Per Area");
        AgentButtonListaAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgentButtonListaAlienActionPerformed(evt);
            }
        });

        AgentButtonRegisterAlien.setText("Register Alien");
        AgentButtonRegisterAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgentButtonRegisterAlienActionPerformed(evt);
            }
        });

        AgentButtonRegisterEquippment.setText("Register New Equipment");
        AgentButtonRegisterEquippment.setMaximumSize(new java.awt.Dimension(188, 23));
        AgentButtonRegisterEquippment.setMinimumSize(new java.awt.Dimension(188, 23));
        AgentButtonRegisterEquippment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgentButtonRegisterEquippmentActionPerformed(evt);
            }
        });

        AgentButtonAlienInfo.setText("Search information on alien");
        AgentButtonAlienInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgentButtonAlienInfoActionPerformed(evt);
            }
        });

        AgentButtonAreaManager.setText("Show  manager of location");
        AgentButtonAreaManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgentButtonAreaManagerActionPerformed(evt);
            }
        });

        AgentButtonStatisticsOfAgent.setText("Show Top 3 Agents with most aliens");
        AgentButtonStatisticsOfAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgentButtonStatisticsOfAgentActionPerformed(evt);
            }
        });

        agentButtonCheckedOutEquippment.setText("Your Checked out Equipment");
        agentButtonCheckedOutEquippment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentButtonCheckedOutEquippmentActionPerformed(evt);
            }
        });

        agentButtonShowListOfAlienRace.setText("Show List of Alien Per Race");
        agentButtonShowListOfAlienRace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentButtonShowListOfAlienRaceActionPerformed(evt);
            }
        });

        agentButtonStatisticsOfRegisteredAliens.setText("List Alien per Regitered Date");
        agentButtonStatisticsOfRegisteredAliens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentButtonStatisticsOfRegisteredAliensActionPerformed(evt);
            }
        });

        jButton1.setText("Take out, Return or View my equipment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        back.setText("Log out");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(AgentButtonAlienInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AgentButtonRegisterAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(agentButtonChangeAlienInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgentButtonListaAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agentButtonStatisticsOfRegisteredAliens)
                            .addComponent(agentButtonShowListOfAlienRace, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(agentButtonCheckedOutEquippment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AgentButtonAreaManager, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(AgentButtonStatisticsOfAgent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AgentButtonRegisterEquippment, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back)))
                .addGap(0, 19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(AgentLableAccess, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AgentLableAccess, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AgentButtonRegisterEquippment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agentButtonCheckedOutEquippment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AgentButtonAreaManager)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AgentButtonStatisticsOfAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AgentButtonRegisterAlien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AgentButtonAlienInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agentButtonChangeAlienInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AgentButtonListaAlien)
                        .addGap(7, 7, 7)
                        .addComponent(agentButtonStatisticsOfRegisteredAliens)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agentButtonShowListOfAlienRace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(back)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgentButtonStatisticsOfAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgentButtonStatisticsOfAgentActionPerformed
        // TODO add your handling code here:
        AgentListTopThreeAgentPerArea frame = new AgentListTopThreeAgentPerArea();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_AgentButtonStatisticsOfAgentActionPerformed

    private void agentButtonShowListOfAlienRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentButtonShowListOfAlienRaceActionPerformed
        // TODO add your handling code here:
        AgentListOfAlienRace frame = new AgentListOfAlienRace();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_agentButtonShowListOfAlienRaceActionPerformed

    private void agentButtonStatisticsOfRegisteredAliensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentButtonStatisticsOfRegisteredAliensActionPerformed
        // TODO add your handling code here:
        AgentListAliensInbetweenDates frame = new AgentListAliensInbetweenDates();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_agentButtonStatisticsOfRegisteredAliensActionPerformed

    private void agentButtonChangeAlienInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentButtonChangeAlienInfoActionPerformed
        // TODO add your handling code here:
        AgentChangeAlienInformation frame = new AgentChangeAlienInformation();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_agentButtonChangeAlienInfoActionPerformed

    private void AgentButtonListaAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgentButtonListaAlienActionPerformed
        // TODO add your handling code here:
        AgentListAlienPerArea frame = new AgentListAlienPerArea();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_AgentButtonListaAlienActionPerformed

    private void AgentButtonRegisterAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgentButtonRegisterAlienActionPerformed
        // TODO add your handling code here:
        AgentAddNewAlien frame = new AgentAddNewAlien();
        frame.setVisible(true);
        dispose();

    }//GEN-LAST:event_AgentButtonRegisterAlienActionPerformed

    private void AgentButtonRegisterEquippmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgentButtonRegisterEquippmentActionPerformed
        // TODO add your handling code here:
        AgentAddNewEquipment_new frame = new AgentAddNewEquipment_new();
        frame.setVisible(true);
        dispose();

    }//GEN-LAST:event_AgentButtonRegisterEquippmentActionPerformed

    private void AgentButtonAlienInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgentButtonAlienInfoActionPerformed
        // TODO add your handling code here:
        AgentListAnAlienInfo frame = new AgentListAnAlienInfo();
        frame.setVisible(true);
        dispose();

    }//GEN-LAST:event_AgentButtonAlienInfoActionPerformed

    private void AgentButtonAreaManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgentButtonAreaManagerActionPerformed
        // TODO add your handling code here:
        AgentFindBossOfLocation frame = new AgentFindBossOfLocation();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_AgentButtonAreaManagerActionPerformed

    private void agentButtonCheckedOutEquippmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentButtonCheckedOutEquippmentActionPerformed
        // TODO add your handling code here:
        AgentListYourCheckedOutEquipment frame = new AgentListYourCheckedOutEquipment();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_agentButtonCheckedOutEquippmentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AgentSignOutEquipment frame = new AgentSignOutEquipment();
        frame.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        StartWindow frame = new StartWindow();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentStartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentStartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentStartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentStartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentStartWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgentButtonAlienInfo;
    private javax.swing.JButton AgentButtonAreaManager;
    private javax.swing.JButton AgentButtonListaAlien;
    private javax.swing.JButton AgentButtonRegisterAlien;
    private javax.swing.JButton AgentButtonRegisterEquippment;
    private javax.swing.JButton AgentButtonStatisticsOfAgent;
    private javax.swing.JLabel AgentLableAccess;
    private javax.swing.JButton agentButtonChangeAlienInfo;
    private javax.swing.JButton agentButtonCheckedOutEquippment;
    private javax.swing.JButton agentButtonShowListOfAlienRace;
    private javax.swing.JButton agentButtonStatisticsOfRegisteredAliens;
    private javax.swing.JButton back;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
